name: PorkPlugin
version: 1.3
author: Alexis Bellido
main: com.zinibu.porkplugin.PorkPlugin

commands:
  hello:
    description: Say hello to everyone!
    usage: /hello

  buildablock:
    description: Build a block
    usage: /buildablock

  buildahouse:
    description: Build a house
    usage: /buildahouse

  spawnacreature:
    description: Spawn a creature
    usage: /spawnacreatute
